# Generated by Django 3.0.7 on 2020-06-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='select',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
