# Generated by Django 3.0.7 on 2020-06-06 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorials', '0002_tutorial_select'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='select',
            field=models.CharField(choices=[('1', '1'), ('2', '2')], default='1', max_length=10),
        ),
    ]
